# Generated by Django 5.0.4 on 2024-05-12 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoice",
            old_name="user_id",
            new_name="created_by",
        ),
    ]
