# Generated by Django 5.0.4 on 2024-05-12 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Customer",
            new_name="Service",
        ),
    ]
