# Generated by Django 5.0.4 on 2024-05-11 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_document"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="description",
        ),
    ]
