# Generated by Django 5.0.4 on 2024-05-11 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0003_remove_document_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="customer_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="customers.customer",
                verbose_name="Customer",
            ),
        ),
    ]
