# Generated by Django 5.0.4 on 2024-05-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0004_document_description_alter_document_customer_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="description",
        ),
        migrations.AddField(
            model_name="customer",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
